### ISSUE TITLE
[Bug] Duplicated article 

### ISSUE THREAD

**Issue by marcinbubolc** [jaktestowac/gad-gui-api-demo#36]
**Describe the bug**
There is no article title validation - you can create as many articles with the same title as you want. 

**To Reproduce**
1. Create an article with simple name for example "Test1"
2. Check if article is present and visible
3. Create another article with the same title "Test1" 
4. Check if there are 2 articles with the same title visible 

**Expected behavior**
Article title validation 

**Screenshots**
![image](https://github.com/jaktestowac/gad-gui-api-demo/assets/119079124/e32879f0-191d-410e-b93a-7aff2e9ee5c5)

**Desktop (please complete the following information):**
 - OS: windows 
 - Browser Chrome
 - Version 125

**Comment by Freudenberger** [comment]
This feature was changed - I reverted old functionality that allows to create articles with same title.

Validation is now placed under **feature flag**.
