### ISSUE TITLE
[Bug] Surname validation on register

### ISSUE THREAD

**Issue by touwinho** [jaktestowac/gad-gui-api-demo#45]
**Describe the bug**
Last name input on Register page doesn't allow to provide two-part surnames. Validation is returning: "Please enter only Letters!"

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/register.html'
2. Fill 'User Last Name' input with two-part surname e.g. "Nowak-Kowalska" 

**Expected behaviour**
After complete rest full form user should be successfully created.

**Screenshots**
![Screenshot 2024-08-27 at 11 20 50](https://github.com/user-attachments/assets/3de8ca0b-a127-4fa4-b1c9-7f848718a5ef)

**Desktop (please complete the following information):**
 - Browser:  Google Chrome v128.0.6613.85
 - GAD Version: v2.7.4
 - OS: MacOS 14.6.1

**Additional context**
Faker.js sometimes returns two-part surname. It is causing a flaky tests. There is no problem to remove '-', but this report may be helpful

**Comment by Freudenberger** [comment]
Fixed (reverted): v2.7.6
