### ISSUE TITLE
[Bug] Primitive example value | schema  

### ISSUE THREAD

**Issue by touwinho** [jaktestowac/gad-gui-api-demo#47]
**Describe the bug**
On Swagger, POST api/flasposts (Create a new flashpost), there is schema with example values to try out. The problem is the schema is only "string", but request also works with set is_public value etc. It's helpful, to create automatic api tests scenarios.

**To Reproduce**
1. Go to '/tools/swagger.html'
2. Scroll down to Flashposts requests
3. Expand POST /api/flashposts
4. Focus on Example Value | Schema

**Expected behavior**
Available schema with more specific properties with: colours, is_public values 

**Screenshots**
![Screenshot 2024-10-02 at 08 44 20](https://github.com/user-attachments/assets/3a15cd19-23b2-407c-b7d8-68f91e210011)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.7
 - Browser: Google Chrome 129.0.6668.71 (Official Build) (arm64)
 - Version: v2.7.5

**Comment by Freudenberger** [comment]
Will be fixed in v2.7.6.
