### ISSUE TITLE
[Bug] Swagger API - flashposts - URL in flashpoint endpoints having duplicated /api element.

### ISSUE THREAD

**Issue by LukegTester** [jaktestowac/gad-gui-api-demo#53]
**Describe the bug**
In GAD swagger API docummentation for flashposts endpoints - executing the command results in requested being send to 'http://localhost:3000/api/api/flashposts' . 
You can see there is duplicated /api element in URL. 
It results in 404 response on some of the request when sending request from swagger. 

**To Reproduce**
Steps to reproduce the behavior: When app run localy :
1. Go to http://localhost:3000/tools/swagger.html 
2. Scroll down to flashposts
3. Send any request described to /flashpost endpoint
4. In request sent data you can see that it is sent to /api/api
5. For some methods like CREATE flashpost it results in http 404 response error when sending from swagger

**Expected behavior**
Api request URL should be 'http://localhost:3000/api/flashposts' . 

**Screenshots**
![kLLhM8J9Lk](https://github.com/user-attachments/assets/4439ab5d-163e-4d4f-8c1a-8affd00e914c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome 131
 - GAD (v2.7.8)

**Additional context**
When running request from different agent, for example postman or UI the request is sent properly to http://localhost:3000/api/flashposts and methods give proper responses and http statuses.

**Comment by LukegTester** [comment]
@Freudenberger sorry, retested on latest GAD version 2.7.9 and is fixed already ! 
INVALID

**Comment by Freudenberger** [comment]
@LukegTester we are really FAST - we fix bugs before they are reported 🤣
